# Generated by Django 5.1.3 on 2024-11-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesite1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date']},
        ),
    ]
